name: Publish Image to Docker Hub

on:
  push:
    branches:
      - main # Change to your default branch
  workflow_dispatch:

jobs:
  publish_image:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: joshlehmandev
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: joshlehmandev/pomodoro-app:latest
          cache-from: type=registry,ref=joshlehmandev/pomodoro-app:latest
          cache-to: type=inline
